<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:datos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:datos">
<types>
<xsd:schema targetNamespace="urn:datos"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="getDatosRequest">
  <part name="parametro1" type="xsd:string" /></message>
<message name="getDatosResponse">
  <part name="return" type="xsd:Array" /></message>
<portType name="Servicio web de x datos!PortType">
  <operation name="getDatos">
    <documentation>Servicio web de x datos!</documentation>
    <input message="tns:getDatosRequest"/>
    <output message="tns:getDatosResponse"/>
  </operation>
</portType>
<binding name="Servicio web de x datos!Binding" type="tns:Servicio web de x datos!PortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="getDatos">
    <soap:operation soapAction="urn:datos#getDatos" style="rpc"/>
    <input><soap:body use="encoded" namespace="urn:datos" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="urn:datos" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="Servicio web de x datos!">
  <port name="Servicio web de x datos!Port" binding="tns:Servicio web de x datos!Binding">
    <soap:address location="http://localhost:8080/localtest/serviciosWeb/servicio.php"/>
  </port>
</service>
</definitions>